-- SQL script to create tables and load sample data
-- Run this after uploading CSVs to DBFS

-- Configuration
-- UPDATE THESE VALUES:
-- SET catalog_name = 'ing_hackathon';
-- SET schema_name = 'sca_advisor';
-- SET data_path = 'dbfs:/FileStore/sca_sample_data/';

-- Create catalog and schema
CREATE CATALOG IF NOT EXISTS ing_hackathon;
CREATE SCHEMA IF NOT EXISTS ing_hackathon.sca_advisor;
USE CATALOG ing_hackathon;
USE SCHEMA sca_advisor;

-- ============================================================================
-- Table: sca_findings
-- Main INPUT table - one row per repo+library combination
-- ============================================================================
DROP TABLE IF EXISTS sca_findings;

CREATE TABLE sca_findings (
    repo_id STRING NOT NULL COMMENT 'Unique identifier for this repo+library',
    repo_path STRING NOT NULL COMMENT 'Databricks repo path',
    repo_name STRING NOT NULL COMMENT 'Human-readable repo name',
    repo_url STRING NOT NULL COMMENT 'Git URL for cloning',
    library STRING NOT NULL COMMENT 'Vulnerable library name',
    current_version STRING NOT NULL COMMENT 'Current installed version',
    priority STRING NOT NULL COMMENT 'Critical, High, Medium, Low',
    cve_ids STRING COMMENT 'JSON array of CVE identifiers',
    cvss_score DOUBLE COMMENT 'CVSS severity score',
    candidate_versions STRING COMMENT 'JSON array of suggested safe versions',
    last_detected_ts TIMESTAMP COMMENT 'When vulnerability was detected',
    status STRING DEFAULT 'ready' COMMENT 'ready, analyzing, approved, rejected',
    checkmarx_finding_id STRING COMMENT 'Link to Checkmarx finding',
    owner_team STRING COMMENT 'Team responsible for this repo'
)
USING DELTA
COMMENT 'Repositories with vulnerable dependencies - one row per repo+library';

-- Load data from CSV
COPY INTO sca_findings
FROM 'dbfs:/FileStore/sca_sample_data/sca_findings.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true');

-- ============================================================================
-- Table: agent_analysis_results (OUTPUT - generated by agent)
-- Output from agent analysis for each repo/version combination
-- ============================================================================
DROP TABLE IF EXISTS agent_analysis_results;

CREATE TABLE agent_analysis_results (
    analysis_id STRING NOT NULL COMMENT 'Unique analysis run ID',
    repo_id STRING NOT NULL COMMENT 'Foreign key to sca_findings',
    target_version STRING NOT NULL COMMENT 'Version being analyzed',
    code_changes_files INT COMMENT 'Number of files to modify',
    code_changes_callsites INT COMMENT 'Number of call sites affected',
    confidence DOUBLE COMMENT 'Agent confidence score (0-1)',
    breaking_changes STRING COMMENT 'JSON list of breaking changes detected',
    analysis_ts TIMESTAMP COMMENT 'When analysis was performed',
    notes STRING COMMENT 'Human-readable summary'
)
USING DELTA
COMMENT 'Agent analysis results for migration scenarios';

COPY INTO agent_analysis_results
FROM 'dbfs:/FileStore/sca_sample_data/agent_analysis_results.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true');

-- ============================================================================
-- Table: user_decisions
-- Audit trail of human approve/reject decisions
-- ============================================================================
DROP TABLE IF EXISTS user_decisions;

CREATE TABLE user_decisions (
    decision_id STRING NOT NULL COMMENT 'Unique decision ID',
    repo_id STRING NOT NULL COMMENT 'Foreign key to sca_findings',
    target_version STRING NOT NULL COMMENT 'Version decision applies to',
    decision STRING NOT NULL COMMENT 'approved or rejected',
    user_email STRING NOT NULL COMMENT 'User who made decision',
    decision_reason STRING COMMENT 'Reason for decision',
    decision_ts TIMESTAMP COMMENT 'When decision was made'
)
USING DELTA
COMMENT 'Audit log of user decisions on migration recommendations';

COPY INTO user_decisions
FROM 'dbfs:/FileStore/sca_sample_data/user_decisions.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true');

-- ============================================================================
-- Table: migration_analysis_results
-- Detailed migration metrics and patch summary
-- ============================================================================
DROP TABLE IF EXISTS migration_analysis_results;

CREATE TABLE migration_analysis_results (
    migration_id STRING NOT NULL COMMENT 'Unique migration analysis ID',
    repo_id STRING NOT NULL COMMENT 'Foreign key to sca_findings',
    library STRING NOT NULL COMMENT 'Library being upgraded',
    from_version STRING NOT NULL COMMENT 'Current vulnerable version',
    to_version STRING NOT NULL COMMENT 'Target safe version',
    breaking_changes_count INT COMMENT 'Number of breaking changes',
    affected_files INT COMMENT 'Files requiring modification',
    affected_invocations INT COMMENT 'Method calls to update',
    patches_generated INT COMMENT 'Total patches created',
    patches_high_confidence INT COMMENT 'High confidence patches',
    patches_medium_confidence INT COMMENT 'Medium confidence patches',
    patches_low_confidence INT COMMENT 'Low confidence patches',
    migration_complexity STRING COMMENT 'low, medium, high',
    estimated_effort_hours DOUBLE COMMENT 'Estimated manual effort in hours',
    auto_fixable_percent DOUBLE COMMENT 'Percentage that can be auto-fixed',
    analysis_ts TIMESTAMP COMMENT 'Analysis timestamp',
    status STRING COMMENT 'completed, pending_review, approved'
)
USING DELTA
COMMENT 'Detailed migration analysis with patch statistics';

COPY INTO migration_analysis_results
FROM 'dbfs:/FileStore/sca_sample_data/migration_analysis_results.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true');

-- ============================================================================
-- Table: generated_patches
-- Individual code patches generated by the agent
-- ============================================================================
DROP TABLE IF EXISTS generated_patches;

CREATE TABLE generated_patches (
    patch_id STRING NOT NULL COMMENT 'Unique patch ID',
    migration_id STRING NOT NULL COMMENT 'Foreign key to migration_analysis_results',
    repo_id STRING NOT NULL COMMENT 'Foreign key to sca_findings',
    file_path STRING NOT NULL COMMENT 'File to modify',
    line_number INT COMMENT 'Line number in file',
    change_type STRING COMMENT 'method_removed, signature_changed, etc.',
    old_code STRING COMMENT 'Original code snippet',
    new_code STRING COMMENT 'Replacement code',
    confidence STRING COMMENT 'high, medium, low',
    explanation STRING COMMENT 'Why this change is needed',
    generated_by STRING COMMENT 'Model that generated patch',
    generation_ts TIMESTAMP COMMENT 'When patch was generated'
)
USING DELTA
COMMENT 'Individual code patches for library migrations';

COPY INTO generated_patches
FROM 'dbfs:/FileStore/sca_sample_data/generated_patches.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true');

-- ============================================================================
-- Verification Queries
-- ============================================================================

-- Show all tables
SHOW TABLES;

-- Count rows in each table
SELECT 'sca_findings' as table_name, COUNT(*) as row_count FROM sca_findings
UNION ALL
SELECT 'agent_analysis_results', COUNT(*) FROM agent_analysis_results
UNION ALL
SELECT 'user_decisions', COUNT(*) FROM user_decisions
UNION ALL
SELECT 'migration_analysis_results', COUNT(*) FROM migration_analysis_results
UNION ALL
SELECT 'generated_patches', COUNT(*) FROM generated_patches;

-- Sample: Critical vulnerabilities ready for analysis
SELECT repo_name, priority, status, last_detected_ts
FROM sca_findings
WHERE priority = 1 AND status = 'ready'
ORDER BY last_detected_ts DESC;
